services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${API_APP_CONTAINER_NAME}
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
