services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${API_APP_CONTAINER_NAME}
    environment:
      - PORT=${PORT}
      - API_APP_CONTAINER_NAME=${API_APP_CONTAINER_NAME}
      - PROJECT_NAME=${PROJECT_NAME}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
