services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api-service-nestjs
    environment:
      - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
